// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetItems() {
  return window['go']['main']['App']['GetItems']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
